name: Smoke test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LEFTHOOK: 0

permissions: {}

jobs:
  smoke-test:
    runs-on: ubuntu-24.04
    container:
      image: gwennlbh/playwright-bun:v1.59.1@sha256:2ea6caacfa3465e6c6ed641cb0ceea0b5d0b467d16398f52caf278e07e0809c3
      options: --user 1001
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Git Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Bun setup
        uses: ./.github/actions/setup

      - name: Smoke & Acceptance tests
        run: bun run test run --project storybook
        env:
          FORCE_COLOR: "1"
