name: Smoke test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LEFTHOOK: 0

permissions: {}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    container:
      image: gwennlbh/playwright-bun:v1.63.0@sha256:3672a4b315f6994598c40360a6b1e5a84252f280ff183656aae5a549227fffbe
      options: --user 1001
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Git Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Bun setup
        uses: ./.github/actions/setup

      - name: Smoke & Acceptance tests
        run: bun run test run --project storybook
        env:
          FORCE_COLOR: "1"
